### ISSUE TITLE
Can you do a release?

### ISSUE THREAD

**Issue by pessoa** [Kixeye/untar-to-s3#3]
I've just written a puppet manifest for untar-to-s3 and I'd like to pin it to a release.
# Class: untar_to_s3
# 
# Installs https://github.com/Kixeye/untar-to-s3 and requirements
# 
# Variables:
# 
# Actions: git clone, pip install boto, pip install gevent
# 
# Requires:
# 
# Sample Usage: Apply to node.
# 
# Authors: SD
# 

class untar_to_s3 {
  package {
    [ 'boto', 'gevent' ]:
      ensure          => present,
      provider        => pip,
  }
  vcsrepo { '/usr/local/SD/untar-to-s3':
    ensure   => present,
    provider => git,
    source   => 'git://github.com/Kixeye/untar-to-s3.git',
    require  => [
      Package['boto'],
    ]
  }
}

**Comment by sobotklp** [comment]
I wasn't planning on doing a release of this code to PyPI as it's just a simple script. Feel free to include the source code verbatim in your puppet module.

**Comment by pessoa** [comment]
can you add a git tag then?

**Comment by sobotklp** [comment]
Sure, just created tag 1.0.0
